pipeline:
  services:
    mongo:
      action: docker:run
      image: mongo:latest
      name: mymongo
      ports:
        27017: 27017

  setup:
    register:
      action: dsunit:register
      datastore: mydb
      ping: true
      config:
        driverName: mgc
        parameters:
          dbname: mydb
          host: 127.0.0.1
          'users.keyColumn': id

    load:
      action: dsunit:prepare
      datastore: mydb
      URL: mydb/data
