init:
  mydbCredentials: pq-mydb-root
  mydbSecrets: ${secrets.$mydbCredentials}
  dbIP:
    pg: 127.0.0.1

pipeline:
  services:
    postgresql:
      action: docker:run
      image: postgres:9.6-alpine
      name: mydb
      ports:
        5432: 5432
      env:
        POSTGRES_USER: ${mydbSecrets.Username}
        POSTGRES_PASSWORD: ${mydbSecrets.Password}

  setup:
    create:
      action: dsunit:init
      datastore: mydb
      config:
        driverName: postgres
        descriptor: host=${dbIP.pg} port=5432 user=[username] password=[password] dbname=[dbname] sslmode=disable
        credentials: $mydbCredentials
      admin:
        datastore: postgres
        ping: true
        config:
          driverName: postgres
          descriptor: host=${dbIP.pg} port=5432 user=[username] password=[password] dbname=postgres sslmode=disable
          credentials: $mydbCredentials
      recreate: true
      scripts:
        - URL: mydb/schema.sql

    load:
      action: dsunit:prepare
      datastore: mydb
      URL: mydb/data