init:
  '!gcpSecrets': $params.authWith
  gcpSecretsMap: $secrets.${gcpSecrets}
  projectID: $gcpSecretsMap.ProjectID

pipeline:
  init:
    action: dsunit:init
    datastore: mydb
    config:
      driverName: fsc
      credentials: $gcpSecrets
      parameters:
        projectID: $projectID

  prepare:
    action: dsunit:prepare
    datastore: mydb
    URL: mydb/data